echo "."
echo "."
echo "."
pkg update && pkg upgrade
pkg install m4
pkg install mplayer
pkg install mpv
pkg install mtools
pkg install mu
pkg install music-file-organizer
pkg install mutt
pkg install myman
pkg install mympd
pkg install mypaint-brushes
pkg install n2n
pkg install nala
pkg install nali
pkg install nano
pkg install navi
pkg install navidrome
pkg install ncdc
pkg install ncdu2
pkg install ncdu
pkg install ncmpcpp
pkg install ncompress
pkg install ncpamixer
pkg install ne
pkg install nelua
pkg install neofetch
pkg install net-tools
pkg install newsboat
pkg install nginx
pkg install ngircd
pkg install ngspice
pkg install nim
pkg install ninja
pkg install nmap
pkg install nodejs
pkg install nudoku
pkg install nushell
pkg install nwipe
pkg install nyancat
pkg install o-editor
pkg install octomap
pkg install opencolorio
pkg install openfoam
pkg install opengl
pkg install openimageio
pkg install openjpeg
pkg install openldap
pkg install openldap
pkg install openmpi
pkg install openscad
pkg install openspecfun
pkg install openssh
pkg install openssl1.1
pkg install openssl
pkg install openvdb
pkg install optipng
pkg install opus-tools
pkg install opusfile
pkg install opusfile
pkg install osm2pgsql
pkg install osmctools
pkg install osmesa
pkg install osmium-tool
pkg install osslsigncode
pkg install ossp-uuid
pkg install p7zip
pkg install pacman-contrib
pkg install pacman
pkg install pacutils
pkg install panda3d-samples
pkg install panda3d
pkg install pandoc
pkg install pangopaperkey
pkg install par2pari
pkg install paruz
pkg install pass-otp
pkg install pastebinit
pkg install pastel
pkg install pathpicker
pkg install pb
pkg install pcal
pkg install pcaudiolib
pkg install pdf2svg
pkg install pdfcpu
pkg install pdftk
pkg install peaclock
pkg install peco
pkg install perl-rename
pkg install petpforth
pkg install photon-rssphp7.2
pkg install php7php
pkg install phpmyadmin
pkg install pianobar
pkg install pick
pkg install plantuml
pkg install play-audio
pkg install playit
pkg install plutolang
pkg install plzip
pkg install pngcrush
pkg install poke
pkg install polipo
pkg install polyml
pkg install poppler
pkg install portaudio
pkg install portmidi
pkg install potrace-sta
pkg install povray
pkg install procps
pkg install procs
pkg install procyon-decompiler
pkg install profanity
pkg install progress
pkg install proj
pkg install proot
pkg install psmisc
pkg install ptunnel
pkg install pulseaudio
puppygobject
pkg install pypy3
pkg install pypy
pkg install pystring
pkg install python2
pkg install python3.10
pkg install python3
pkg install python3.9
pkg install python
pkg install ruby
pkg install unpaper
pkg install unrar
pkg install unshield
pkg install unzip
pkg install update-info-dir
pkg install w3m-img
pkg install weechat-perl-plugin
pkg install weechat-python-plugin
pkg install weechat-ruby-plugin
pkg install weechat
pkg install wego
pkg install wget2
pkg install wget
pkg install wgetpaste
pkg install wol
pkg install wordgrinder
pkg install wren
pkg intsall wrk
pkg install wtfutil
pkg install wuzz
pkg install wv-tools
pkg install yarn
pkg install yosys
pkg install youtubedr
pkg install ytfzf
pkg install ytui-music
pkg install yuma123
pkg install zip
pkg install zpaq
pkg install zphisher
lolcat "Berhasil Di Install !"